I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 183, in script
    GRV "พวกเขาต้องการข้าว มาก และ มากขึ้น สิ่งนั้นทำให้โลกนี้มีทุ่งนาอยู่ถึง 70-98%"
ValueError: incomplete format

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 183, in script
    GRV "พวกเขาต้องการข้าว มาก และ มากขึ้น สิ่งนั้นทำให้โลกนี้มีทุ่งนาอยู่ถึง 70-98%"
  File "D:\renpy-8.3.4-sdk\renpy\ast.py", line 2579, in execute
    Say.execute(self)
  File "D:\renpy-8.3.4-sdk\renpy\ast.py", line 621, in execute
    renpy.exports.say(who, what, *args, **kwargs)
  File "D:\renpy-8.3.4-sdk\renpy\exports\sayexports.py", line 121, in say
    what = what % tag_quoting_dict
ValueError: incomplete format

Windows-10-10.0.22631 AMD64
Ren'Py 8.3.4.24120703
NE_VN 1.0
Sun Jan 26 01:36:20 2025
